import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
	index("routes/home.tsx"),
	route("upload", "routes/upload.tsx"),
	route("gallery", "routes/gallery.tsx"),
	route("rising-stars", "routes/rising-stars.tsx"),
	route("art/:key", "routes/art.$key.tsx"),
	route("vote/:key", "routes/vote.$key.tsx"),
	route("updates", "routes/updates.tsx"),
	route("board", "routes/board.tsx"),
	route("games", "routes/games.tsx"),
	route("spore-field", "routes/spore-field.tsx"),
	route("lunar-buggy", "routes/lunar-buggy.tsx"),
	route("galaga", "routes/galaga.tsx"),
	route("defender", "routes/defender.tsx"),
	route("bug-blaster", "routes/bug-blaster.tsx"),
	route("bug-blaster/online", "routes/bug-blaster.online.tsx"),
	route("bug-blaster/room/:code", "routes/bug-blaster.room.$code.tsx"),
	route("moon-patrol", "routes/moon-patrol.tsx"),
	route("galaxy-swarm", "routes/galaxy-swarm.tsx"),
	route("galaxy-swarm/online", "routes/galaxy-swarm.online.tsx"),
	route("galaxy-swarm/room/:code", "routes/galaxy-swarm.room.$code.tsx"),
	route("api/game-click", "routes/api.game-click.tsx"),
	route("api/high-scores", "routes/api.high-scores.tsx"),
	route("daily", "routes/daily.tsx"),
	route("draw-battle", "routes/draw-battle.tsx"),
	route("guess", "routes/guess.tsx"),
	route("guess/room/:code", "routes/guess.room.$code.tsx"),
	route("fake-artist", "routes/fake-artist.tsx"),
	route("fake-artist/room/:code", "routes/fake-artist.room.$code.tsx"),
	route("squiggle", "routes/squiggle.tsx"),
	route("squiggle/room/:code", "routes/squiggle.room.$code.tsx"),
	route("doodle", "routes/doodle.tsx"),
	route("doodle/room/:code", "routes/doodle.room.$code.tsx"),
	route("draw-battle/online", "routes/draw-battle.online.tsx"),
	route("draw-battle/room/:code", "routes/draw-battle.room.$code.tsx"),
	route("admin", "routes/admin.tsx"),
	route("admin/login", "routes/admin.login.tsx"),
] satisfies RouteConfig;
